### DISCUSSION TITLE
How to publish a Tailwind plugin or styles?

### DISCUSSION THREAD

**Discussion by CarcajadaArtificial** [jsr-io/jsr#1129] [Q&A]
Hello, I'm finding myself using the same custom styles in many of my projects. They look like this

```css
@theme { ... }
:root { ... }
@plugin "daisyui/theme" { ... }
@layer base { ... }
@layer components { ... }
@layer utilities { ... }
...
```

I usually import these styles as:

```css
@import "tailwindcss";
@import "./custom_styles.css"; /* Here */
@plugin "@tailwind/typography";
@plugin "@daisyui" {
  themes: false;
}
```

But for this, I'm forced to individually and manually update all my stylesheets in all of my projects. I have a utility library published on JSR, how can I publish these styles for them to be imported on my projects. I'm using Deno Fresh v2, Tailwind v4, DaisyUI v5.

Thank you
