### ISSUE TITLE
The File Viewer seems to be corrupted.

### ISSUE THREAD

**Issue by totto2727** [jsr-io/jsr#256]
At least in my environment (Mac + Arc), the following page does not seem to render correctly.
This `display: block` seems to override the `code` tag's `display: flex`.

https://jsr.io/@oak/oak/14.2.0/request.ts

<img width="2515" alt="スクリーンショット 2024-03-09 20 59 04" src="https://github.com/jsr-io/jsr/assets/61417777/9dc20022-fa9f-4ef6-82e8-fd3937a57e21">

I checked with the developer tools and it seems that the following classes of CSS have a higher priority and override the expected style. 

```css
.ddoc .markdown pre>code:first-child {
  /* padding: 1rem; */
  /* This `display: block` seems to override the `code` tag's `display: flex`. */
  display: block;
  overflow-x: auto;
}
```

<img width="874" alt="スクリーンショット 2024-03-09 21 06 34" src="https://github.com/jsr-io/jsr/assets/61417777/cdbccc1f-d012-4eea-9095-20e54eec68f3">

I commented out `display: block` and confirmed that it renders correctly.

<img width="1440" alt="スクリーンショット 2024-03-09 21 14 31" src="https://github.com/jsr-io/jsr/assets/61417777/35621677-8fd8-4440-953e-4e3170870406">
