### ISSUE TITLE
Bug: openapi schema, `rekorLogId` should be nullable

### ISSUE THREAD

**Issue by HuakunShen** [jsr-io/jsr#885]
I am using the openapi schema (https://api.jsr.io/.well-known/openapi) to generate client.
And I noticed an error in the schema 

Here is the schema for `rekorLogId`
```yaml
rekorLogId:
          type: string
          description: Rekor log ID for the published package version.
```

But when a package isn't signed by github action, its `rekorLogId` is null.
I believe a `nullable: true` should be added to the schema.
